### ISSUE TITLE
Add support for txt

### ISSUE THREAD

**Issue by zdila** [crocodilejs/node-email-templates#176]
Add support for `txt` in `{{ext}}`. We'd like to use `subject.txt` without any substitution.

**Comment by niftylettuce** [comment]
@zdila Have you any luck here?  Not sure if you forked this yet and there's a pull request you were going to make.  Thank you! ✨

**Comment by niftylettuce** [comment]
Released v2.4.1 to NPM, thanks for your pull request @homerjam!
