### ISSUE TITLE
How to pass express variable to .jade email template file

### ISSUE THREAD

**Issue by nuruddeensalihu** [crocodilejs/node-email-templates#180]
Hi,

Thank you for this wonderful tool. I have tried sending my email and the template is working. My problem is sending variables back to my template . Please see my question of on stackoverflow http://stackoverflow.com/questions/37899584/how-to-pass-express-variable-to-jade-email-template-file . I m using jade engine for my template . Please your help is appreciated.

**Comment by niftylettuce** [comment]
Have you figured this out yet @nuruddeensalihu?  If not, please share code example.

**Comment by nuruddeensalihu** [comment]
@niftylettuce yah . Thank you for tour time
