### ISSUE TITLE
How do I pass the template options for nunjucks

### ISSUE THREAD

**Issue by redaz808** [crocodilejs/node-email-templates#182]
Hi,

I am trying to pass a filter to use in the nunjucks templates. Example:

```
var env = new nunjucks.Environment();
 env.addFilter('shorten', function(str, count) {
    return str.slice(0, count || 5);
});

var newsletter = new emailTemplate(path.join(templatesDir, templateFile),{
            env: env
});

When I pass the template name, I am getting the following error:
 [Template render error: (unknown path)
  Error: filter not found: shorten] name: 'Template render error' }
```

Any idea how can I use the template filters? Any help is appreciated.
Thanks,

**Comment by aeharding** [comment]
I'm trying to do the same thing with little success. Because the templates are rendered in the current working directory instead of relative to where the EmailTemplate is instantiated...

**Comment by aeharding** [comment]
Well, I was messing around and did something like this:

```js
    // Set the directory for template path resolving
    // used by email-templates => consolidate.js => nunjucks
    // (otherwise it will default to the CWD)
    const settings = {
        views: path.join(__dirname, '../')
    };


    template.render({ settings, otherViewModelStuff })
    .then(...)
```

No documentation, I had to look at the source. :)

You can also pass `loader` directly into consolidate.js, and/or add nunjucks directly to `loader.nunjucks` on `const emailer = require('email-templates')`

**Comment by niftylettuce** [comment]
Wow I'm really sorry.  Can you submit a PR @aeharding with documentation for this?  😦 I didn't think I let this package slide that much!!!!

**Comment by niftylettuce** [comment]
@aeharding ping

**Comment by timelf123** [comment]
I ran into this issue today and may be missing something, but was unable to get @aeharding solution working yet

**Comment by niftylettuce** [comment]
@aeharding @timelf123 Hey, thanks to both of you for discussing this. Here I am months later and ran into the exact same problem for my new framework https://github.com/crocodilejs/crocodile-node-mvc-framework... I will be updating documentation for this shortly.

**Comment by niftylettuce** [comment]
So it appears that `renderString` is used in `consolidate`, and of which it does not support `includes` per <https://github.com/mozilla/nunjucks/issues/730>.

**Comment by timelf123** [comment]
Any idea how to get `env` working? I am trying to add a custom filter like OP
```
var env = new nunjucks.Environment();
env.addFilter('nl2br', function(str) {
    return str.replace(/\r|\n|\r\n/g, '<br />')
})

  var options = {
    settings: {
      views: path.join(__dirname, 'templates'),
      env: env
    }
  };

```

**Comment by niftylettuce** [comment]
@timelf123 take a look at how I did https://github.com/crocodilejs/crocodile-node-mvc-framework/blob/development/src/jobs/index.js - I actually stopped using this package (`email-templates`) in favor of the approach I took in that code.  Anyways, if you wanted to use a custom env for this package, you could do so by the latest which supports my fork of consolidate.js, see the Readme note here https://github.com/niftylettuce/consolidate.js#notes

**Comment by timelf123** [comment]
Pretty slick thanks for the example @niftylettuce. Unfortunately I'm not able to use all the ES6 wonderfulness quite yet

With your new approach/focus on crocodilejs, does that mean shuttering support for `email-templates`?

**Comment by niftylettuce** [comment]
Yeah I'll probably refactor it @timelf123 completely or build something new!

**Comment by niftylettuce** [comment]
@timelf123 really this wrapper is kind of useless IMO, I built something beautiful in CrocodileJS per link above which I plan to componentize.

**Comment by niftylettuce** [comment]
Please use latest version `v2.5.4` from NPM via `npm install --save email-templates@latest`.  Thank you.  If you need documentation on Nunjucks see notes in <https://github.com/tj/consolidate.js/#notes>.
