### ISSUE TITLE
Build fail on dependency url format.

### ISSUE THREAD

**Issue by sohara** [crocodilejs/node-email-templates#197]
Hi there, the latest release results in a build failure in our CI environment (jenkins):
```
12:02:46.339 npm ERR! node v0.10.40
12:02:46.339 npm ERR! npm  v2.7.1
12:02:46.340 
12:02:46.340 npm ERR! Unsupported URL Type: github:niftylettuce/consolidate.js
12:02:46.341 npm ERR! 
```

Oddly it doesn't seem to be a problem on my local development system.

**Comment by albertosouza** [comment]
See https://docs.npmjs.com/files/package.json#github-urls
Can change `github:niftylettuce/consolidate.js` to `niftylettuce/consolidate.js`

**Comment by sohara** [comment]
Yes, that change would probably fix it... do you want a pr?

**Comment by niftylettuce** [comment]
Yeah please

**Comment by niftylettuce** [comment]
see 2.5.2
