### ISSUE TITLE
npm install -S email-templates: code 128 or ENOGIT

### ISSUE THREAD

**Issue by Frosty-Z** [crocodilejs/node-email-templates#198]
Hi,

I get a very strange behavior here since version 2.5.2 on a project using email-templates.

`npm install -S email-templates` throws either a bunch of 'addRemoteGit' warnings ending with a "ENOGIT error", or if git is installed, I get this kind of error :

```
npm ERR! node v4.6.0
npm ERR! npm  v3.10.8
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\Maxime\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:niftylettuce/consolidate.js.git C:\Users\Maxime\AppData\Roaming\npm-cache\_git-remotes\git-github-com-niftylettuce-consolidate-js-git-26f53914
npm ERR! Cloning into bare repository 'C:\Users\Maxime\AppData\Roaming\npm-cache\_git-remotes\git-github-com-niftylettuce-consolidate-js-git-26f53914'...
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
```

Apparently in both cases, it attempts & fails to fetch the package **consolidate.js** from github.

Note that previous release `npm install -S email-templates@2.4.1` installs without any problem.

Ran on babun/cygwin on Windows 10.

With regards.

**Comment by DaveKlassen4** [comment]
I have the exact same configuration, and the same error, so for now I am locking on v2.4.1, but it would be nice to continue on the new release version.

**Comment by niallobrien** [comment]
Windows isn't officially supported though. 🤔

**Comment by danieleds** [comment]
Same thing on Linux.

This is a serious issue with automatic deployments.
The package "consolidate.js" should be available on npm, even just for a fact of "version safety".

Sticking with v2.4.1 for now.

**Comment by niftylettuce** [comment]
Hi everyone - I just was given collaborator status on consolidate.js and I will be publishing a new version of it, and subsequently a new version of email templates.  Thanks for your patience.

**Comment by niftylettuce** [comment]
Please use latest version v2.5.4 from NPM via `npm install --save email-templates@latest`.
