### ISSUE TITLE
Using embedded images

### ISSUE THREAD

**Issue by iamchathu** [crocodilejs/node-email-templates#211]
Can we keep image files in template folder and refer them in template and send as embedded images in email?

**Comment by niftylettuce** [comment]
@iamchathu yes - I recommend you use https://github.com/crocodilejs/nodemailer-base64-to-s3 after embedding the images as base64.  You can embed them as base64 by passing an option to juice...

```
juiceOptions: {
  webResources: {
    relativeTo: path.join(__dirname, '..', '..', 'build') // path to folder where your images are
  }
}
```

however you seem like you're really getting into things here, so I might recommend you actually take a look at how I send emails with CrocodileJS (which doesn't use `email-templates`, it just uses `juice` strictly by itself and `nodemailer`).  https://github.com/crocodilejs/crocodile-node-mvc-framework/blob/development/src/jobs/index.js

**Comment by iamchathu** [comment]
I tried adding relativeTo: but it didn't worked 😢

**Comment by iamchathu** [comment]
@niftylettuce  Can we embed images without uploading to s3?

**Comment by niftylettuce** [comment]
@iamchathu not really, that's the whole reason why I made those packages
