### ISSUE TITLE
display image in a template ejs

### ISSUE THREAD

**Issue by zevenements** [crocodilejs/node-email-templates#214]
Hello !
I've got a problem to render a png in a email:

-image is in : public/img/picture.png

-my middleware express is ok with : 
`app.use(express.static(__dirname + '/public')); `

-i'm using the ejs engine : 
html.ejs
```
<div>
  <img src="img/picture.png">
</div>
```
....some style and text

The email received is ok, exept the image which is doesn't inside... 
any idea ?
thanks

**Comment by niftylettuce** [comment]
and you should pass juice options to convert the image you pass using web inline resources options for `juice` CTRL/CMD+F (search) for `juiceOptions` mentioned in the Readme here https://github.com/crocodilejs/node-email-templates to see how you can pass options to juice.  you'll probably want to pass options that we do in CrocodileJS at https://github.com/crocodilejs/crocodile-node-mvc-framework/blob/development/src/jobs/index.js#L137-L142 - I actually don't use this package anymore, I use a similar setup to the link I just gave.  It's a bit easier to work with.  You should join us in Slack at http://slack.crocodilejs.com and we can help more
